package com.example.taskmanager.database;


import jakarta.persistence.*;

/**
 * *******************************************************
 * Package: com.example.taskmanager.database
 * File: TaskJpaEntity.java
 * Author: Ochwada
 * Date: Monday, 23.Jun.2025, 11:37 AM
 * Description:
 * Objective:
 * *******************************************************
 */



@Entity
@Table(name = "tasks")
public class TaskJpaEntity {

    /**
     * Unique identifier for the task.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String title;

    private String description;

    private boolean completed;

    public TaskJpaEntity() {
        // Required by JPA
    }

    /**
     * Full constructor used to initialize all fields of the task.
     *
     * @param title       the task's title
     * @param description a detailed description of the task
     * @param completed   the task's completion status
     */
    public TaskJpaEntity( String title, String description, boolean completed) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.completed = completed;
    }

    public TaskJpaEntity(String description, boolean completed) {
        this.id = id;
        this.description = description;
        this.completed = completed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isCompleted() {
        return completed;
    }

    /**
     * Sets the task's completion status.
     *
     * @param completed true if completed, false otherwise
     */
    public void setCompleted(boolean completed) {
        this.completed = completed;
    }
}
