package com.example.companyhr.model;


import jakarta.persistence.*;

/**
 * *******************************************************
 * Package: com.example.companyhr.model
 * File: Employee.java
 * Author: Ochwada
 * Date: Monday, 30.Jun.2025, 9:58 AM
 * Description: Represents an Employee Entity in a company's HR system.
 * * The Employee entity represents a record in the employee table.
 * * It contains basic attributes such as name, department, and salary.
 * Objective:
 * *******************************************************
 */

@Entity
@Table(name = "Employees")
public class Employee {

    /**
     * The unique identifier for the employee.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the employee.
     */
    private String name;

    /**
     * The department in which the employee works.
     */
    private String department;

    /**
     * The employee's salary.
     */
    private Double salary;

    /**
     * Default constructor for JPA.
     * Required by frameworks that instantiate the entity via reflection.
     */
    public Employee() {
    }

    /**
     * Constructs a new Employee with the given name, department, and salary.
     *
     * @param name       the employee's name
     * @param department the department where the employee works
     * @param salary     the employee's salary
     */
    public Employee(String name, String department, Double salary) {
        this.name = name;
        this.department = department;
        this.salary = salary;
    }

    // ---------------------------------------------------------------
    // Getters and Setters (or use Lombok's @Getter/@Setter)
    // ---------------------------------------------------------------
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public Double getSalary() {
        return salary;
    }

    public void setSalary(Double salary) {
        this.salary = salary;
    }
}
